Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -4,41 +4,66 @@ pipeline {
         jdk 'JAVA_HOME'
         nodejs 'nodejs25'
     }
-    
+
     stages {
-        
-        stage ("Git Checkout") {
+
+        stage("Git Checkout") {
             steps {
                 git 'https://github.com/Prashant4656/DevOps-Project-Zomato-Kastro.git'
             }
         }
-     
-    stage ("Build Docker Image") {
+
+        stage("Build Docker Image") {
             steps {
                 sh "docker build -t prashant4656/zomatoapp:1.0 ."
             }
         }
-    stage ("Tag & Push to DockerHub") {
+
+        stage("Tag & Push to DockerHub") {
             steps {
                 script {
-                    withCredentials([usernamePassword(credentialsId: 'docker-login', passwordVariable: 'dockerhubpass', usernameVariable: 'dockerhublogin')]) {
+                    withCredentials([usernamePassword(credentialsId: 'docker-login',
+                            passwordVariable: 'dockerhubpass',
+                            usernameVariable: 'dockerhublogin')]) {
+
                         sh 'docker login -u ${dockerhublogin} -p ${dockerhubpass}'
-                        sh "docker push prashant4656/zomatoapp:1.0  "
+                        sh "docker push prashant4656/zomatoapp:1.0"
                     }
                 }
             }
         }
+
         stage('Config & Deployment') {
             steps {
-                
-                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'awslogin', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
+
+                withCredentials([
+                    aws(credentialsId: 'awslogin',
+                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
+                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'),
+                    
+                    file(credentialsId: 'bookmyshow_pem', variable: 'PEMFILE')
+                ]) {
+
                     dir('terraformfiles') {
-                    sh 'terraform init'
-                    sh 'terraform validate'
-                    sh 'terraform apply --auto-approve -var="pem_file=$PEMFILE"'
-}
+
+                        sh '''
+                            echo "PEMFILE = $PEMFILE"
+                            ls -l "$PEMFILE"
+
+                            if [ -d "$PEMFILE" ]; then
+                                echo "❌ ERROR: PEMFILE points to a directory, not a file"
+                                exit 1
+                            fi
+
+                            chmod 600 "$PEMFILE"
+
+                            terraform init
+                            terraform validate
+                            terraform apply --auto-approve -var="pem_file=$PEMFILE"
+                        '''
+                    }
+                }
+            }
+        }
     }
-}
-}
-}
 }
